apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-express
  labels:
    app: mongo-express
spec:
  replicas: {{ .Values.deployment.mongoExpress.spec.replicas }}
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: {{ .Values.deployment.mongoExpress.image }}
        ports:
        - containerPort: {{ .Values.deployment.mongoExpress.spec.port.containerPort }}
        resources: {{ .Values.deployment.mongoExpress.spec.resources }}
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: ME_CONFIG_MONGODB_SERVER 
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: db_host
