apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: {{ .Values.deployment.mongoExpress.spec.type }}  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: {{ .Values.deployment.mongoExpress.spec.nodePort }}