apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: {{ .Values.deployment.mongodb.secret.username | b64enc }}
  password: {{ .Values.deployment.mongodb.secret.password | b64enc }}