apiVersion: v1
kind: Pod
metadata:
 name: tom1-cat
spec:
 containers:
 - name: tomcat1-cat
   image: tomcat:8.0
   ports:
    - containerPort: 7500
 - name: database
   image: mongo
   ports:
    - containerPort: 7501
    # - port: 3000
   imagePullPolicy: Always
