apiVersion: v1
kind: Pod
metadata:
 name: multi-Pod
spec:
#  containers:
#   - name: busybox1
#     image: busybox
#   - name: busybox2
#     image: busybox
containers:
  - args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox1
    resources: {}
  - args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: busybox2