apiVersion: v1
kind: Pod
metadata:
 name: web-app
spec:
 containers:
  - name: mongodb
    image: mongo
    ports:
    - containerPort: 27017
    imagePullPolicy: Always
  - name: mongo-express
    image: mongo-express
    ports:
    - containerPort: 8081
    imagePullPolicy: Always
  - name: webapp
    image: sancho27/webapp:1.0
    ports:
    - containerPort: 3000
    imagePullPolicy: Always

